"use client";
import {useEffect,useRef,useState} from 'react';
import {startVisiblePolling} from "@/lib/visible-polling";
import {reviewErrorMessage,isStorageLimitError} from "@/lib/storage-error";
import Link from 'next/link';
import {contentWorkflow,finalApprovalReady} from '@/lib/content-workflow';
import {WorkflowChecklist} from '@/components/workflow-checklist';
import type {AronReviewItem} from '@/lib/aron-review-queue';
import '../published/published.css';
export default function Attention(){
 const [records,setRecords]=useState<AronReviewItem[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState('');
 const inFlight=useRef(false);
 async function load(){if(inFlight.current)return;inFlight.current=true;setLoading(true);setError('');try{const response=await fetch('/api/aron/review-queue',{cache:'no-store'});const data=await response.json();if(!response.ok)throw new Error(data.error||'Content could not be loaded.');setRecords(data.records||[]);return true;}catch(e){setError(reviewErrorMessage(e,'Could not load content.'));return false;}finally{inFlight.current=false;setLoading(false);}}
 useEffect(()=>startVisiblePolling(load),[]);
 const pending=records.filter(r=>!r.reviewArchivedAt&&!r.reviewDeletedAt&&!contentWorkflow(r).done&&r.wordpressStatus!=='trash');
 const visible=pending.filter(r=>finalApprovalReady(r)&&[r.practiceArea,r.clientName,r.city,r.state,r.website].join(' ').toLowerCase().includes(search.toLowerCase())).sort((a,b)=>Number(finalApprovalReady(b))-Number(finalApprovalReady(a)));
 return <main className="app-shell"><header className="topbar"><Link className="brand" href="/attention"><span className="brand-mark">A</span><span className="brand-word">AMPLIFY</span></Link><div className="topbar-actions"><Link className="secondary-button compact" href="/editorial-calendar">Calendar</Link><Link className="secondary-button compact" href="/published">Published</Link><Link className="secondary-button compact" href="/">Create / manage content</Link></div></header><section className="publication-library"><div className="publication-heading"><div><h1>Ready for your approval</h1><p>Aron approves the writing. AMPLIFY prepares and checks the WordPress draft. You preview it and approve.</p></div><button className="secondary-button compact" disabled={loading} onClick={()=>void load()}>{loading?'Loading…':'Refresh'}</button></div><div className="publication-filters"><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Client, title or location"/></label><Link className="secondary-button compact" href="/editorial-calendar">Choose upcoming topics</Link></div>{error&&<p role="alert">{error} {!isStorageLimitError(error)&&<a href="/api/google/connect">Reconnect Google</a>}</p>}{!loading&&!error&&<p>{visible.length} items · {pending.filter(finalApprovalReady).length} ready for your approval</p>}{!loading&&!error&&!visible.length&&<p>No finished pages are waiting for your final approval. AMPLIFY will add them here after preparation and checks pass.</p>}<div className="publication-list">{visible.map(r=>{const flow=contentWorkflow(r),ready=finalApprovalReady(r);return <article className="publication-row" key={r.id}><div><div className="publication-meta">{r.clientName||r.website} · {flow.label}</div><h2>{r.workflow==='enhance' ? r.docName || r.pageUrl || r.website : [r.city,r.state,r.practiceArea].filter(Boolean).join(' ')}</h2><p>{r.error||r.draftWarnings?.[0]||flow.note}</p><WorkflowChecklist record={r}/></div><Link className="primary-button compact" href={r.aronDone?`/final-review/${r.id}`:r.docUrl?'/aron':`/?record=${encodeURIComponent(r.id)}`}>{ready?'Review & approve':r.aronDone?'See work in progress':r.docUrl?'Open Aron review':'Open writing task'}</Link></article>;})}</div></section></main>;
}
